### ISSUE TITLE
suggestion: concise sexual positions

### ISSUE THREAD

**Issue by enkephalin07** [bbepis/KoikatsuTranslation#10]
These labels are falling off the buttons; more concise terms would fit the space better and make it easier to discuss them. Descriptively cumbersome names aren't particularly sexy, either.

**Comment by DarkPulse** [comment]
Where is this, game or studio?

Studio should have text that auto-scrolls for them, but to my knowledge, there is nothing for the game proper in our stuff yet (some third-party UI mods might have something though). Admittedly they do tend to be more "overly descriptive," but to be fair, so were the originals.

Can you give a screenshot or two?

**Comment by DarkPulse** [comment]
**_UPDATE_**

We've narrowed this down to be due to AutoTranslator - it will read any/all strings and apply them blindly, ignoring some features that our DynamicTranslator plugin has (specifically in this case, the flags that tell it to load only during specific levels/while specific EXEs are running). Disabling the AutoTranslator will make it so that the files are only loaded by DynamicTranslator, and enable the extra restrictions.

AutoTranslator needs to be updated to support this, which is out of our purview and not something that Bepis coded. While I will eventually shorten these labels in some form (probably once I get to properly doing the H-Scene stuff and seeing how it unfolds), for now, this isn't technically an issue with the actual translation. Thus, closing report.

Contact whoever is developing AutoTranslator now, and let them know they need to support at least those flags. If they need to, they can get in touch with Bepis and he will provide them more information.
